/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    application
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("software.amazon.awscdk:aws-cdk-lib:2.136.0")
    api("software.constructs:constructs:[10.0.0,11.0.0)")
    implementation(project(":lambda")) // Dependency to lambda project
    testImplementation("org.junit.jupiter:junit-jupiter:5.7.1")
}

description = "infrastructure"
java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

application {
    mainClass = "io.github.wtfjoke.CarbonAwareServerlessJobsQuarkusApp"
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
